export const reducerCases = {
  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
  SET_CURRENTLY_PLAYING: "SET_CURRENTLY_PLAYING",
  SET_IS_PLAYING: "SET_IS_PLAYING",
  SET_CUSTOM_MINUTES: "SET_CUSTOM_MINUTES",
  SET_CUSTOM_SECONDS: "SET_CUSTOM_SECONDS",
};
